### ISSUE TITLE
Move documentation to JSDoc

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whs.js#233]
There is a JSDoc support for **Readme.io** - [link here](https://readme.io/swagger/)

I'd like to see it working with this project. How about moving docs there? It will be easier to maintain them.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [x] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
What about using [jsdoc](http://usejsdoc.org/) and push the generated doc to surge?

**Comment by sasha240100** [comment]
@hirako2000 Maybe use [some integrations](http://swagger.io/open-source-integrations/) to use it for library API ?

**Comment by hirako2000** [comment]
@thejmazz , what do you think?

**Comment by thejmazz** [comment]
I don't think swagger is useful here, as @hirako2000 mentions - it is for documenting REST APIs. 

It does seem very useful to have HTML documentation generated from code comments. JSDoc is great, and has a bunch of to-markdown, to-html tools. Maybe something like [typedoc](https://github.com/TypeStrong/typedoc) would work as well. 

I'm curious how whs-specific features (e.g. "this component is compatible with module x", or "module y requires the `position` and `rotation` properties on the component") could be generated in an automatic way.

**Comment by hirako2000** [comment]
I don't think generated doc is all that useful right now.
probably better put some effort in typings, which give an incentive to provide human readable comment to functions and properties since they are exposed for typescript users.

I suggest we close this for now. provide clearer doc in readme.io where appropriate, more examples & some guides.

The source code ultimately is needed for understanding the core logic to extend certain components and create modules.

**Comment by hirako2000** [comment]
Progress on issue #189
